# Generated by Django 2.2.1 on 2019-09-12 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_book_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish',
            new_name='p',
        ),
    ]
